const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const makeDOM=require('./test-dom.cjs');const root=path.resolve(__dirname,'../dist');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const catalogs={id:JSON.parse(read('locales/id.json')),en:JSON.parse(read('locales/en.json'))};
function placeholders(s){return [...s.matchAll(/\{([a-zA-Z][\w]*)\}/g)].map(m=>m[1]).sort().join('|')}
assert.equal(Object.keys(catalogs.id).sort().join(),Object.keys(catalogs.en).sort().join());for(const key of Object.keys(catalogs.id)){assert.equal(typeof catalogs.en[key],'string',key);if(catalogs.id[key].length)assert(catalogs.en[key].length,key);assert.equal(placeholders(catalogs.id[key]),placeholders(catalogs.en[key]),'Placeholder mismatch: '+key)}
const fixtures=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/model-results.json'),'utf8'));
const freshHistory=location=>({state:null,replaceState(state,_,url){this.state=state;location.href=new URL(url,location.href).href;const parsed=new URL(location.href);location.hash=parsed.hash;location.search=parsed.search},pushState(state,title,url){this.replaceState(state,title,url)}});
async function runtime(lang='id',page='index.html',saved=null,extra={}){const dom=makeDOM(read(page)),errors=[],memory=new Map(saved?[['system-design-lab.language',saved]]:[]),location={href:'https://example.test/'+page+(lang?'?lang='+lang:''),hash:'',search:lang?'?lang='+lang:''};const fetch=async url=>{const file=new URL(url).pathname.slice(1);const data=extra[file];return{ok:true,status:200,json:async()=>data||JSON.parse(read(file))}};const context={...dom,location,history:freshHistory(location),localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},fetch,URL,URLSearchParams,Intl,AbortController,CustomEvent:class{constructor(type,opts){this.type=type;this.detail=opts.detail}},console:{log(){},error:(...a)=>errors.push(a.join(' '))},setInterval,clearInterval};vm.createContext(context);vm.runInContext(read('locales/registry.js'),context);vm.runInContext(read('i18n.js'),context);await context.window.I18n.ready;return{context,dom,errors,memory}}
function numbers(value,key='',out={}){if(typeof value==='number'){assert(Number.isFinite(value),'Nonfinite '+key);out[key]=value}else if(value&&typeof value==='object')for(const [k,v]of Object.entries(value))numbers(v,key+'.'+k,out);return out}
function unresolved(value){if(typeof value==='string'){assert(!/\[(?:c\d\d\.|ui\.|legacy\.)/.test(value),'Unresolved key: '+value);assert(!/\{[a-zA-Z][\w]*\}/.test(value),'Unresolved parameter: '+value)}else if(Array.isArray(value))value.forEach(unresolved);else if(value&&typeof value==='object')Object.values(value).forEach(unresolved)}
async function loadCourse(env){const c=env.context;c.window.COURSE_FACTORIES=[];for(const f of fs.readdirSync(path.join(root,'modules')).filter(f=>f.endsWith('.js')))vm.runInContext(read('modules/'+f),c,{filename:f});await vm.runInContext(read('course.js'),c);return c.window.COURSE_FACTORIES.flatMap(f=>f((k,p)=>c.window.I18n.t(k,p))).sort((a,b)=>a.id-b.id)}
async function main(){let comparisons=0,views=0,interactions=0;
for(const lang of ['id','en']){const env=await runtime(lang),{context:c,dom}=env;const modules=await loadCourse(env);assert.equal(modules.length,28);assert.equal(modules.map(m=>m.id).join(),Array.from({length:28},(_,i)=>i+1).join());assert.equal(dom.document.documentElement.lang,lang);assert.equal(env.errors.length,0,env.errors.join('\n'));
 for(const f of fixtures){const m=modules.find(m=>m.id===f.id);assert.equal(JSON.stringify(m.lab.defaults),JSON.stringify(f.defaults),'Default changes '+m.id);for(const sample of f.samples){const result=m.lab.evaluate(Object.freeze({...sample.state}));assert.deepEqual(numbers(result),sample.numeric,'Numerical regression '+lang+' '+m.id+' '+sample.name);unresolved(result);for(const bar of result.bars||[]){assert(bar.value>=0&&bar.max>0)}comparisons++}}
 const open=dom.tools.find(t=>t.name==='open_system_design_chapter'),configure=dom.tools.find(t=>t.name==='configure_system_design_lab');assert(open&&configure);
 for(const m of modules){unresolved(m);assert(m.sections.length>=5);for(const mode of ['lab','learn','exercise']){open.execute({chapter:m.id,mode});const html=dom.elements.get('content').innerHTML;assert(html.length>100);unresolved(html);views++}if(m.legacy)continue;open.execute({chapter:m.id,mode:'lab'});for(let i=0;i<m.lab.presets.length;i++){await dom.document.querySelector(`[data-preset="${i}"]`).fire('click');unresolved(dom.elements.get('lab-results').innerHTML);interactions++}for(const control of m.lab.controls){const el=dom.elements.get('input-'+control.key);el.value=control.type==='select'?control.options.at(-1).value:control.max;await el.fire(control.type==='select'?'change':'input');interactions++}await dom.elements.get('reset-lab').fire('click');assert.throws(()=>configure.execute({values:{invalidParameter:1}}))}
 // A language change must preserve the active chapter, mode, numeric settings, and values.
 open.execute({chapter:2,mode:'lab'});const module=modules.find(m=>m.id===2),preset=module.lab.presets[0].values;const before=configure.execute({values:preset});await c.window.I18n.setLocale(lang==='id'?'en':'id');const after=configure.execute({values:{}});assert.equal(after.chapter,before.chapter);assert.equal(JSON.stringify(after.values),JSON.stringify(before.values));assert.deepEqual(numbers(after.metrics),numbers(before.metrics));assert.equal(dom.document.documentElement.lang,lang==='id'?'en':'id');assert.equal(env.memory.get('system-design-lab.language'),lang==='id'?'en':'id');assert(new URL(c.location.href).searchParams.get('lang'));
 open.execute({chapter:4,mode:'lab'});const frame=dom.elements.get('legacy-frame');await c.window.I18n.setLocale(lang);assert.equal(dom.elements.get('legacy-frame'),frame,'Legacy iframe replaced during switch');assert.equal(frame.childLocale,lang);assert.throws(()=>open.execute({chapter:29}));assert.equal(env.errors.length,0,env.errors.join('\n'));
}
const saved=await runtime(null,'index.html','en');assert.equal(saved.context.window.I18n.locale,'en');const invalid=await runtime('unknown');assert.equal(invalid.context.window.I18n.locale,'id');
// New language, plural categories, RTL metadata, fallback, and rejected language writes.
const env=await runtime('en','index.html',null,{'locales/test.json':{'ui.lab':'Test lab','test.items.one':'{count} item','test.items.other':'{count} items'}});env.context.window.SDL_LOCALE_CONFIG.languages.push({code:'xx',name:'Test',intl:'en-US',dir:'rtl',file:'locales/test.json'});vm.runInContext(read('i18n.js'),env.context);await env.context.window.I18n.ready;const i=env.context.window.I18n;await i.setLocale('xx');assert.equal(i.t('ui.lab'),'Test lab');assert.equal(i.t('ui.learn'),catalogs.id['ui.learn']);assert.equal(i.t('test.items',{count:1}),'1 item');assert.equal(i.t('test.items',{count:2}),'2 items');assert.equal(env.dom.document.documentElement.dir,'rtl');await assert.rejects(i.setLocale('not-registered'));assert.equal(i.locale,'xx');
// Legacy lab math and states across locale updates; source injection exists only in this test.
let legacyChecks=0;for(const lang of ['id','en']){const env=await runtime(lang,'legacy.html');env.context.window.I18n.setLocale=env.context.window.I18n.setLocale.bind(env.context.window.I18n);const src=read('app.js').replace(/\}\)\(\);\s*$/,`window.__labTest={scaleModel,sendRequests,advance,boundary,mappings,ring,selectLab,renderAll,get state(){return {s,r,h}},setRateAlgorithm(a){r.algorithm=a;resetRate();}};})();`);await vm.runInContext(src,env.context);const api=env.context.window.__labTest;assert(api);for(const algorithm of ['token','fixed','sliding']){api.setRateAlgorithm(algorithm);api.boundary();assert.equal(api.state.r.accepted,algorithm==='fixed'?20:10);legacyChecks++}const before=JSON.stringify(api.state);await env.context.window.I18n.setLocale(lang==='id'?'en':'id');assert.equal(JSON.stringify(api.state),before);for(const lab of ['scaling','rate','hash']){api.selectLab(lab);api.renderAll();unresolved(env.dom.elements.get('metrics').innerHTML);legacyChecks++}assert.equal(env.errors.length,0,env.errors.join('\n'))}
for(const page of ['index.html','legacy.html'])for(const match of read(page).matchAll(/(?:src|href)="([^"#]+)"/g)){const ref=match[1];if(!/^(https?:|data:)/.test(ref))assert(fs.existsSync(path.join(root,ref.split('?')[0])),'Missing asset: '+ref)}
console.log(JSON.stringify({locales:['id','en'],catalogKeys:Object.keys(catalogs.id).length,chapters:28,numericComparisons:comparisons,renderedViews:views,uiInteractions:interactions,legacyChecks,statePreservation:true,fallbackAndRTL:true,browserQA:'Not performed; DOM/event harness only'},null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1});
